input {

  beats {
    port => 5044
  }

  file {
    path => "/threatdata/alerts/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }

  file {
    path => "/threatdata/alerts/mitigation_log.txt"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }

}

filter {

  ####################################
  # 1️⃣ MITIGATION LOGS
  ####################################

  if [message] =~ /ACTION=/ {

    grok {
      match => {
        "message" => "\[%{TIMESTAMP_ISO8601:timestamp}\]\sACTION=%{WORD:action}\s\|\sDETAILS=%{GREEDYDATA:details}"
      }
    }

    date {
      match => ["timestamp","yyyy-MM-dd HH:mm:ss"]
      target => "@timestamp"
    }

    mutate {
      add_field => {
        "engine" => "mitigation_engine"
        "status" => "mitigated"
      }
    }

  }

  ####################################
  # 2️⃣ DETECTION ALERTS
  ####################################

  else if [message] =~ /triggered/ {

    grok {
      match => {
        "message" => "\[%{TIMESTAMP_ISO8601:timestamp}\]\s\[%{WORD:severity}\]\s%{DATA:attack_type}\striggered\s-\sLine\s%{NUMBER:line_number}:\s%{GREEDYDATA:log_message}"
      }
    }

    date {
      match => ["timestamp","yyyy-MM-dd HH:mm:ss"]
      target => "@timestamp"
    }

    mutate {
      add_field => {
        "engine" => "detection_engine"
        "status" => "detected"
      }
    }

  }

}

####################################
# OUTPUT
####################################

output {

  if [engine] == "detection_engine" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "threat-alerts"
    }
  }

  else if [engine] == "mitigation_engine" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "threat-mitigation"
    }
  }

}